### ISSUE TITLE
Bug: Game crashing  - possibly when used with snooper?

### ISSUE THREAD

**Issue by clytemnestra** [Blooym/Wholist#43]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit my report.

### Bug Behavior

```
2023-10-16 16:59:06.059 +03:00 [ERR] [WindowSystem] Error during Draw(): [Wholist] Nearby Players
System.NullReferenceException: Object reference not set to an instance of an object.
   at Wholist.DataStructures.PlayerInfoSlim.get_Distance() in /work/repo/Wholist/DataStructures/PlayerInfoSlim.cs:line 86
   at Wholist.UserInterface.Windows.NearbyPlayers.NearbyPlayersWindow.DrawPlayer(PlayerInfoSlim obj) in /work/repo/Wholist/UserInterface/Windows/NearbyPlayers/NearbyPlayers.window.cs:line 143
   at Dalamud.Interface.Utility.ImGuiClip.ClippedDraw[T](IReadOnlyList`1 data, Action`1 draw, Single lineHeight) in C:\goatsoft\companysecrets\dalamud\Interface\Utility\ImGuiClip.cs:line 54
   at Wholist.UserInterface.Windows.NearbyPlayers.NearbyPlayersWindow.DrawNearbyPlayersTable(List`1 playersToDraw) in /work/repo/Wholist/UserInterface/Windows/NearbyPlayers/NearbyPlayers.window.cs:line 91
   at Wholist.UserInterface.Windows.NearbyPlayers.NearbyPlayersWindow.Draw() in /work/repo/Wholist/UserInterface/Windows/NearbyPlayers/NearbyPlayers.window.cs:line 62
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 329
```

I get this in my logs, I am using this with snooper and after spending <1 minute in crowded areas, my game simply poofs.

### Expected Behavior

It was fine before the latest patch, I am unsure if there is an incompatibility with snooper or something else.

### Steps To Reproduce

use wholist and snooper, go to limsa and game crashes after <1 minute there, dalamud logs have that error a few times and that's all.

**Comment by Blooym** [comment]
I can't seem to replicate this behaviour after installing snooper and having it open for around 5 minutes in Limsa. I have the feeling this issue is caused by something completely different so I'm going to push an update that may (or may not) fix this
